### ISSUE TITLE
{artist} tag not working with playlist downloads - Error: 'NoneType' object has no attribute 'artist' at playlist/(id)

### ISSUE THREAD

**Issue by xiliourt** [oskvr37/tiddl#217]
# EDIT:
Adding a custom config file fixed this, even with the **default settings**. I think somewhere in the code it's using '{artist}' instead of the new {item.artist} maybe? Or something like that. Only applies to playlist/mixes.

### What command was used?

tiddl download url https://tidal.com/mix/00295a98210f9028aa8f01c9fe83fd

(or any other playlist / mix URL)

### What happened?

Gives an error about NoneType not containing {artist}

# Output (debug is the same)
```
~ # tiddl download url https://tidal.com/mix/00295a98210f9028aa8f01c9fe83fd
Auth token expires in 0d 0h 58m
Error: 'NoneType' object has no attribute 'artist' at
mix/00295a98210f9028aa8f01c9fe83fd
Total downloads: 0
```

Edit: The old template settings are outdated and no longer used it appears - so it was with the default template this was happening. This is also confirmed by the schema of how tracks and albums downloaded.

Tracks and albums work fine. This is the template I've used previously and it worked on 2.5.1

### Python version

3.14

### What operating system are you using?

Linux (Docker)

### Relevant log output
Nothing relevant in logs, just shows a hit for the playlist, then pulling 20  items

2025-11-13 20:36:25,285 DEBUG   [tiddl.core.api.client.fetch] playlists/(id) {'countryCode': 'BR'} 'HIT' [200]
2025-11-13 20:36:25,592 DEBUG   [tiddl.core.api.client.fetch] playlists/(id)/items {'countryCode': 'BR', 'limit': 20, 'offset': 0} 'HIT' [200]

CountryCode is 'br' for some reason also - when my account is NG (it use to detect that), not an issue though - works fine still. It may result in unexpected restrictions though, but BR isn't a bad country restriction wise on tracks.

**Comment by xiliourt** [comment]
api_debug looks as per expected - is formatted as per schema.

**Comment by xiliourt** [comment]
So adding a custom config.toml fixed this? It seems there's a glitch when one isn't present - it must default to something incorrect?

**Comment by xiliourt** [comment]
> The issue is that we can't use `{album}` in playlists templates. When we fetch a playlist, the tracks don't have full album object - only some fields:
> 
> class Track(BaseModel):
>     class Album(BaseModel):
>         id: int
>         title: str
>         cover: Optional[str] = None
>         vibrantColor: Optional[str] = None
>         videoCover: Optional[str] = None
> There are 2 solutions:
> 
> * fetch full album info on every track from playlist, which will lead to more API hits
> * add `{item.album}` template, which will have less info about albums
> 
> I will work on fixing this

For some reason it worked when I used a config file just with default settings, I'm not sure why though. Maybe that forced it to use item.artist / album.artist (whatever the default is)

**Comment by oskvr37** [comment]
> For some reason it worked when I used a config file just with default settings, I'm not sure why though. Maybe that forced it to use item.artist / album.artist (whatever the default is)

It shouldn't work with default settings lol

Default template is `"{album.artist}/{album.title}/{item.title}"` and while we download a playlist, the album data is not available for template formatter, so it should raise error.

I will fix it anyway
